<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="2.595" timestamp="2023-10-06T18:53:21.035388" hostname="delas-desktop"><testcase classname="" name="tests.model.test_model" time="0.000"><error message="collection failure">ImportError while importing test module '/home/delas/Downloads/challenge_MLE/tests/model/test_model.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/model/test_model.py:6: in &lt;module&gt;
    from challenge.model import DelayModel
challenge/__init__.py:1: in &lt;module&gt;
    from challenge.api import app
challenge/api.py:4: in &lt;module&gt;
    from model import DelayModel
E   ModuleNotFoundError: No module named 'model'</error></testcase></testsuite></testsuites>